### ISSUE TITLE
`Проверить на сайте` button is useless

### ISSUE THREAD

**Issue by Ilanaya** [mkangoo/Telegram-bot-schedule#15]
Currently, the user should download `xlsx` file with the schedule and find the info there which is VERY painful on mobile (I tried once :))

I suggest replacing the button link with this:
`https://my.guu.ru/student/classes/mobile`

This will open a mobile version of the schedule for everyone who has site student access

**Comment by mkangoo** [comment]
When choosing a link, I was guided as follows:
1. As I know, in your personal account the schedule is managed with a delay, and it is not always correct.
2. Some users do not have the ability to quickly enter their personal account, they need to find their password, etc.

I agree that downloading a file is not the best idea (by the way, a month ago, when I checked the functionality of the buttons and made changes to the schedule, it was possible to view the schedule without downloading).
I gave two links to three students in the group, all three voted for this option (download `xlsx` file)

**Comment by mkangoo** [comment]
@Ilanaya I suggest this option
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/68b9ec16-54a8-4171-bbc7-06134cc9c413)

1. [Check on the website](https://my.guu.ru/student/classes/mobile)  
2. [Download schedule](https://guu.ru/student/schedule/)

**Comment by Ilanaya** [comment]
Looks cool
