### ISSUE TITLE
Problems on the server with displaying the schedule

### ISSUE THREAD

**Issue by mkangoo** [mkangoo/Telegram-bot-schedule#25]
Checking the week number:
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/502cc87e-a4f1-45af-b9eb-8aebe079cdeb)
I check the schedule for Thursday using the `week_schedule` command:
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/819378c5-0793-49c9-ae74-78221763ca6c)
Everything is correct, the schedule corresponds!
I check the schedule for Thursday using the built-in keyboard:
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/f3e2b5a3-3296-43e2-a577-9d88b4c5d255)
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/2958f833-2393-4703-b27c-96c261e627aa)
The schedule is incorrect. The third pair of practice will only be in weeks 4 and 6.
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/7df8d4c5-b364-4de6-9934-106ade107d4d)

**Comment by mkangoo** [comment]
I don’t understand what this is connected with. When testing the bot locally, there are no problems. Also, after restarting the bot on the server, the problems disappear. I have attached a screenshot of the local bot, it displays everything correctly:
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/4cc15728-42ce-4232-8da7-73e438f975ac)

**Comment by mkangoo** [comment]
Maybe it's worth changing the hosting and writing more tests to display the schedule?

**Comment by mkangoo** [comment]
@Ilanaya What do you think might be causing this problem and how can it be caught?

**Comment by Ilanaya** [comment]
I'll check today

**Comment by Ilanaya** [comment]
What do you mean under `restarting the bot`? If this fixes a problem we need to know what exactly happens on restart

> Also, after restarting the bot on the server, the problems disappear.

**Comment by mkangoo** [comment]
I do this via GUI:
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/7d856281-561f-4094-9fa9-c272fe684ed3)
I can also look at the build logs and application logs. I'm interested in the second one, but there are no errors there, which is very strange.

**Comment by mkangoo** [comment]
I restarted and everything worked correctly, you can verify this by going to [Bot](https://t.me/scheduleGuuBot)

**Comment by Ilanaya** [comment]
I don't know what was the problem and how to detect it. Maybe something was outdated on the server.

But we definitely need to work on bot's architecture and add more tests

**Comment by Ilanaya** [comment]
@mkangoo Can this issue be closed? Or you are currently working on tests or smth?

If the problem is reproduced again you can always reopen
