### ISSUE TITLE
Add `tsconfig.json`

### ISSUE THREAD

**Issue by Ilanaya** [mkangoo/Telegram-bot-schedule#26]
Add `tsconfig.json` file at the root of the project. The basic setup like below should be fine for now. You can add more features if you need.

```json
{
	"include": ["src/**/*"],
	"compilerOptions": {
		"noEmit": true,
		"checkJs": true,
		"allowJs": true,
		"strict": true,
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"module": "esnext",
		"lib": ["esnext"],
		"moduleResolution": "node"
	}
}
```
We don't use ts in the project but some extensions determine whether the current project is javascript or typescript written by the `tsconfig.json` presence. IMO, most of the time it is better to pretend that your project is written with ts as extensions may disable some features if they don't find tsconfig in the root.

**Comment by mkangoo** [comment]
@Ilanaya Thanks,i didn t know about this.I added the `tsconfig` file to the project.
