### ISSUE TITLE
`/show` command hides keyboard, `/hide` command opens it

### ISSUE THREAD

**Issue by Ilanaya** [mkangoo/Telegram-bot-schedule#6]
After `/show` command nothing happens if the keyboard is closed.
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/74474615/e25256f9-d86c-4154-92e2-7637219c5f13)

After `/hide` command keyboard opens
![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/74474615/28a66aeb-1ddc-4e13-88b0-6743de384d45)

**Comment by mkangoo** [comment]
Thank you for the detailed description.
1.After `/hide` it is expected to open the keyboard for entering commands. I think it is more convenient for the user to use reply buttons. I added the option to hide reply buttons to be able to control the bot only with commands.
2.After entering a command `/show` or `/hide` there is no check if the keyboard is hidden or open.
Do you think it is necessary to add such a check?

**Comment by Ilanaya** [comment]
@mkangoo Hm, can we consider removing these commands entirely? 

1. Their current behaviour is really strange - I didn't even expect the `/hide` command to open something
2. Native tg buttons (menu bar on the left, inline keyboard button on the right) look like more native way to do what `/show` and `/hide` commands do + the user needs even more clicks to invoke this commands than get the desired result using native buttons.

**Comment by mkangoo** [comment]
@Ilanaya I agree with you.  I think it needs to be fixed
