### ISSUE TITLE
Bot improvements

### ISSUE THREAD

**Issue by Ilanaya** [mkangoo/Telegram-bot-schedule#7]
1.  The first letter in the `Contacts` work is  Russian 'C' :) 
https://github.com/mkangoo/Telegram-bot-schedule/blob/040d68d3547e614b166f21affd66396ce12923b7/src/contactMe.js#L4
2.  How do you develop the bot? I don't have commands menu button in the left corner by default

![image](https://github.com/mkangoo/Telegram-bot-schedule/assets/74474615/4657b5cc-af59-4ace-9a8c-51b339ffc6f7)

If I understand it correctly you either add bot commands [with Bot father or invoke `setMyCommands` with command list](https://core.telegram.org/bots/features#commands:~:text=for%20this%20to%20work%2C%20you%20need%20to%20have%20provided%20a%20list%20of%20commands%20to%20%40BotFather%20or%20via%20the%20appropriate%20API%20method). I think we should use the second method as adding them manually is annoying (tbh I spent a lot of time to figure out why I don't have this menu by default). 

With `Telegraf` lib you can do this with [`bot.telegram.setMyCommands(...)`](https://telegraf.js.org/classes/Telegram.html#setMyCommands)

3. As you can see [here](https://core.telegram.org/bots/features#global-commands) Telegram has some mandatory commands for bots. `Telegraph` library has some methods to do this
For the `/start` command: [`bot.start()`](https://telegraf.js.org/classes/Telegraf-1.html#start)
For the `/help` command: [`bot.help()`](https://telegraf.js.org/classes/Telegraf-1.html#help). You can just ignore it if you don't want to. The expected command output described [here](https://core.telegram.org/bots/features#global-commands:~:text=/help%20%2D%20returns%20a%20help%20message%2C%20like%20a%20short%20text%20about%20what%20your%20bot%20can%20do%20and%20a%20list%20of%20commands.)

**Comment by Ilanaya** [comment]
Install `cSpell` vscode extension to forget about issues like the first in the comment above. Very useful for checking grammar

**Comment by mkangoo** [comment]
Thank you for the detailed description!

1.Yes, you are right. I have the cSpell extension installed. I was inattentive)

![Снимок экрана от 2024-02-15 15-36-58](https://github.com/mkangoo/Telegram-bot-schedule/assets/121447049/33f37e43-ae65-4d0e-9097-b063349cc416)
2.I used the first method. You are right, it would be better to use `bot.telegram.setMyCommands(...)`
