### ISSUE TITLE
`/schedule` command does the same as  `Текущая неделя` button in inline keyboard

### ISSUE THREAD

**Issue by Ilanaya** [mkangoo/Telegram-bot-schedule#9]
I suggest:
1. Change `/shedule` command logic to display full schedule in one message without need to choose the day.
2. Add commands for each option, i.e. /today, /tomorrow .... and rename `/scheduleCommad` to `/weekSchedule`

I think first option is more preferred. As least I expected this command to work as I described in the first option

**Comment by Ilanaya** [comment]
@mkangoo Btw, can you open PR's for each issue fix instead of pushing to master next time? It'll be much easier to track issue related changes.

**Comment by mkangoo** [comment]
@Ilanaya
1.Do you think it would be convenient to view the schedule from your phone if it went out in its entirety for the week? 
2.Good idea, I'll do it.

**Comment by mkangoo** [comment]
You may need to specify the day of the week for the schedule.
We need to think about how best to do this.

**Comment by Ilanaya** [comment]
1. Don't quite understand the message in the  comment above previous. You worry about resulting message length? I don't think it is a problem at all. Moreover there is no other way to see the whole week schedule except manually clicking on each day which is very annoying
2. I don't think we even need commands like /today, /tomorrow etc. This logic should be **only** in inline keyboard as this is the main bot's functionality and inline keyboard is the most convenient way to use the bot.

I suggest we separate bot logic:
- The most useful commands should go to inline keyboard
- Extra functionality and complex logic should be placed in commands
